# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e04bbfb00d532cd1be81e126ba33af0f12ae0d28c4d68d900f4ed3d6849744a8fe1500df969796e0e3892a79be5d125b4b0eb4422c0cf4ad7f9bde751a6dcb85

test:
  secret_key_base: b5bb3aaf21671e663ad5732cf3a828295ab31d412c9b776a1f9b431e884504220ff60f5584f201999558a46140cb65f26d3ce342fa73a2712dce2e0a8e223328

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
