# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48a92de5ed29788a3b17d4b3d7d6dd626dc08e4f6efa56418e793cace53436c332e2c4d0d646295c8f3559afefd50d2af43a81e441e202312d69b1ee9c872163

test:
  secret_key_base: 5431fb3120195170b0cf860d3ed8e0ce030d30b81a0185531501f80b4aef4a87c90cb0a52cc2712e45425d1f49f7180871bcc4fd83f7c252c7ddc2c13bf6bdfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
